service: app

provider:
    name: aws
    region: eu-central-1
    runtime: provided
    apiGateway:
        binaryMediaTypes:
            - 'image/png'
    environment:
        BREF_BINARY_RESPONSES: 1

plugins:
    - ./vendor/bref/bref

functions:
    countdown:
        handler: public/handler.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - arn:aws:lambda:eu-central-1:209497400698:layer:php-74-fpm:5
        events:
            -   http: 'GET /'
            -   http: 'GET /{to}'

# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
